In [ ]:
# necessary imports
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
# creating environment
env = gym.make("FrozenLake-v1")

In [ ]:
# initializing q-table
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# initializing all parameteters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
# algorithm implementaion
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
  state = env.reset()

  done = False
  rewards_current_episode = 0

  for step in range(max_steps_per_episode):

    # exploration-exploitation trade-off
    exploration_rate_threshold = random.uniform(0,1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action = env.action_space.sample()
    
    new_state, reward, done, info = env.step(action)

    # update Q-table for Q(s,a)
    q_table[state, action] = q_table[state, action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state,:]))

    state = new_state
    rewards_current_episode += reward

    if done == True:
      break
  
  # exploration rate decay
  exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

  rewards_all_episodes.append(rewards_current_episode)

In [ ]:
# calculate and print the average reward per thousand episodes
count = 1000
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/count)
print("*****Average reward per thausand episodes*****\n")
for r in rewards_per_thousand_episodes:
  print(count, ":", str(sum(r/1000)))
  count+=1000;

*****Average reward per thausand episodes*****

1000 : 0.04500000000000003
2000 : 0.21900000000000017
3000 : 0.35900000000000026
4000 : 0.5870000000000004
5000 : 0.6200000000000004
6000 : 0.6710000000000005
7000 : 0.6860000000000005
8000 : 0.6860000000000005
9000 : 0.6740000000000005
10000 : 0.6680000000000005


In [ ]:
# print q_table
print("\n\n*****Q-table*****\n\n")
print(q_table)



*****Q-table*****


[[0.47129797 0.47054587 0.47101052 0.46897604]
 [0.24535199 0.3448077  0.27037403 0.45323587]
 [0.39779092 0.41080704 0.3843316  0.44148571]
 [0.32367197 0.26110743 0.32741901 0.42588539]
 [0.48096943 0.38581093 0.31124659 0.27705927]
 [0.         0.         0.         0.        ]
 [0.36638427 0.13140013 0.23177526 0.15131954]
 [0.         0.         0.         0.        ]
 [0.23945653 0.34903785 0.37801906 0.51422176]
 [0.45397282 0.57431574 0.48163758 0.5020686 ]
 [0.61151512 0.43678207 0.29483756 0.27663104]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.34654315 0.44981361 0.69187042 0.45060853]
 [0.76169411 0.88690919 0.78480179 0.78219928]
 [0.         0.         0.         0.        ]]


In [ ]:
# playing the game
import os
import gym
os.environ["SDL_VIDEODRIVER"] = "dummy"
env = gym.make("FrozenLake-v1")

for episode in range(3):
  state = env.reset()
  done = False
  print("--EPISODE:", episode+1,"--\n")
  time.sleep(1)

  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action=np.argmax(q_table[state,:])
    new_state, reward, done, info = env.step(action)

    if done:
      clear_output(wait=True)
      env.render()
      if reward == 1:
        print("You reached the goal")
        time.sleep(3)
      else:
        print("you fell through hole")
        time.sleep(3)
      clear_output(wait=True)
      break

    state=new_state

env.close()

You reached the goal
